package hexapodsimulator;

/**
 * Dialog for copying of intervals
 * @author peter
 */
public class IntervalCopyDialog extends javax.swing.JDialog {

    private String name;
    private boolean cancelled;
    private boolean beginCropped;
    private int beginCropTime;
    private boolean endCropped;
    private int endCropTime;

    /** Creates new form IntervalCopyDialog */
    public IntervalCopyDialog(java.awt.Frame parent, String name, int duration) {
        super(parent, true);
        initComponents();
        newNameTextField.setText(name + "_copy");
        newNameTextField.setSelectionStart(0);
        newNameTextField.setSelectionEnd(newNameTextField.getText().length());
        cropBeginTextField.setText("0");
        cropEndTextField.setText(Integer.toString(duration));
        getRootPane().setDefaultButton(copyButton);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newNameTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        cropBeginCheckBox = new javax.swing.JCheckBox();
        cropBeginLabel1 = new javax.swing.JLabel();
        cropBeginTextField = new javax.swing.JTextField();
        cropEndCheckBox = new javax.swing.JCheckBox();
        cropBeginLabel2 = new javax.swing.JLabel();
        cropEndLabel1 = new javax.swing.JLabel();
        cropEndTextField = new javax.swing.JTextField();
        cropEndLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        copyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("New name:");

        cropBeginCheckBox.setText("crop Begin:");
        cropBeginCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cropBeginCheckBoxActionPerformed(evt);
            }
        });

        cropBeginLabel1.setText("to");
        cropBeginLabel1.setEnabled(false);

        cropBeginTextField.setEnabled(false);

        cropEndCheckBox.setText("crop End:");
        cropEndCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cropEndCheckBoxActionPerformed(evt);
            }
        });

        cropBeginLabel2.setText("millisec.");
        cropBeginLabel2.setEnabled(false);

        cropEndLabel1.setText("from");
        cropEndLabel1.setEnabled(false);

        cropEndTextField.setEnabled(false);

        cropEndLabel2.setText("millisec.");
        cropEndLabel2.setEnabled(false);

        copyButton.setText("Copy");
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(newNameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cropBeginCheckBox)
                            .add(cropEndCheckBox))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cropBeginLabel1)
                            .add(cropEndLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(cropEndTextField)
                            .add(cropBeginTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cropEndLabel2)
                            .add(cropBeginLabel2)))
                    .add(layout.createSequentialGroup()
                        .add(copyButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(newNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cropBeginCheckBox)
                    .add(cropBeginTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cropBeginLabel2)
                    .add(cropBeginLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cropEndCheckBox)
                    .add(cropEndLabel1)
                    .add(cropEndTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cropEndLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(copyButton)
                    .add(cancelButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cropBeginCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cropBeginCheckBoxActionPerformed
        boolean state = cropBeginCheckBox.isSelected();
        beginCropped = state;
        cropBeginLabel1.setEnabled(state);
        cropBeginLabel2.setEnabled(state);
        cropBeginTextField.setEnabled(state);
    }//GEN-LAST:event_cropBeginCheckBoxActionPerformed

    private void cropEndCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cropEndCheckBoxActionPerformed
        boolean state = cropEndCheckBox.isSelected();
        endCropped = state;
        cropEndLabel1.setEnabled(state);
        cropEndLabel2.setEnabled(state);
        cropEndTextField.setEnabled(state);
    }//GEN-LAST:event_cropEndCheckBoxActionPerformed

    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        name = newNameTextField.getText();
        beginCropTime = Integer.parseInt(cropBeginTextField.getText());
        endCropTime = Integer.parseInt(cropEndTextField.getText());
        dispose();
    }//GEN-LAST:event_copyButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancelled = true;
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    public String getNewName() {
        return name;
    }

    public boolean isBeginCropped() {
        return beginCropped;
    }

    public int getBeginCropTime() {
        return beginCropTime;
    }

    public boolean isEndCropped() {
        return endCropped;
    }

    public int getEndCropTime() {
        return endCropTime;
    }

    public boolean isCancelled() {
        return cancelled;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton copyButton;
    private javax.swing.JCheckBox cropBeginCheckBox;
    private javax.swing.JLabel cropBeginLabel1;
    private javax.swing.JLabel cropBeginLabel2;
    private javax.swing.JTextField cropBeginTextField;
    private javax.swing.JCheckBox cropEndCheckBox;
    private javax.swing.JLabel cropEndLabel1;
    private javax.swing.JLabel cropEndLabel2;
    private javax.swing.JTextField cropEndTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField newNameTextField;
    // End of variables declaration//GEN-END:variables

}
